id = "racket"
name = "Racket"
description = "Racket support."
version = "0.1.0"
schema_version = 1
authors = ["Mikayla Maki <mikayla@zed.dev>"]
repository = "https://github.com/zed-extensions/racket"

[language_servers.racket-lsp]
name = "racket-lsp"
language = "Racket"

[grammars.racket]
repository = "https://github.com/zed-industries/tree-sitter-racket"
commit = "beb29de2b668110e69df0c6d51649c3e2c91d863"
